name: yard

dependencies:
- base
- containers
- text

default-extensions:
- DisambiguateRecordFields
- NoFieldSelectors
- OverloadedRecordDot
- DerivingStrategies
- BlockArguments
- LambdaCase
- ImportQualifiedPost
- NamedFieldPuns
- DeriveFunctor
- ScopedTypeVariables
- GeneralizedNewtypeDeriving

ghc-options: -freverse-errors -Wall -Werror

library:
  source-dirs: src